/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FundRouteImport } from './routes/fund'
import { Route as IndexRouteImport } from './routes/index'

const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fund': typeof FundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fund': typeof FundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fund': typeof FundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fund'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fund'
  id: '__root__' | '/' | '/fund'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundRoute: typeof FundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundRoute: FundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
